name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Create temp .yarnrc.yml without yarnPath
      run: |
        # Extract content from .yarnrc.yml but exclude the yarnPath line
        grep -v "yarnPath:" .yarnrc.yml > .yarnrc.yml.tmp
        mv .yarnrc.yml.tmp .yarnrc.yml
      shell: bash

    - name: Setup Yarn with Corepack
      run: |
        corepack enable
        yarn set version 3.6.1
      shell: bash
      
    - name: Create plugin directory and install plugins
      run: |
        mkdir -p .yarn/plugins
        yarn plugin import @yarnpkg/plugin-interactive-tools
        yarn plugin import @yarnpkg/plugin-workspace-tools
      shell: bash

    - name: Restore cache
      uses: actions/cache/restore@v4
      id: yarn-cache
      with:
        path: |
          **/node_modules
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash

    - name: Save cache
      uses: actions/cache/save@v4
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      with:
        path: |
          **/node_modules
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
        key: ${{ steps.yarn-cache.outputs.cache-primary-key || format('{0}-yarn-{1}-{2}', runner.os, hashFiles('yarn.lock'), hashFiles('**/package.json', '!node_modules/**')) }}